from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.WindowModality.NonModal)
        MainWindow.setEnabled(True)
        MainWindow.resize(1464, 780)
        MainWindow.setMinimumSize(QtCore.QSize(1464, 780))
        MainWindow.setMaximumSize(QtCore.QSize(1464, 780))
        font = QtGui.QFont()
        font.setPointSize(12)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.AccountFrame = QtWidgets.QFrame(parent=self.centralwidget)
        self.AccountFrame.setGeometry(QtCore.QRect(20, 20, 521, 191))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.AccountFrame.setFont(font)
        self.AccountFrame.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.AccountFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.AccountFrame.setObjectName("AccountFrame")
        self.gridLayout = QtWidgets.QGridLayout(self.AccountFrame)
        self.gridLayout.setVerticalSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.password_text = QtWidgets.QLineEdit(parent=self.AccountFrame)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        self.password_text.setFont(font)
        self.password_text.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.password_text.setObjectName("password_text")
        self.gridLayout.addWidget(self.password_text, 1, 1, 1, 5)
        self.account_label = QtWidgets.QLabel(parent=self.AccountFrame)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        self.account_label.setFont(font)
        self.account_label.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.account_label.setObjectName("account_label")
        self.gridLayout.addWidget(self.account_label, 0, 0, 1, 1)
        self.accounts_box = QtWidgets.QComboBox(parent=self.AccountFrame)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        self.accounts_box.setFont(font)
        self.accounts_box.setEditable(True)
        self.accounts_box.setInsertPolicy(QtWidgets.QComboBox.InsertPolicy.NoInsert)
        self.accounts_box.setDuplicatesEnabled(True)
        self.accounts_box.setObjectName("accounts_box")
        self.gridLayout.addWidget(self.accounts_box, 0, 1, 1, 5)
        self.password_label = QtWidgets.QLabel(parent=self.AccountFrame)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        self.password_label.setFont(font)
        self.password_label.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.password_label.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.password_label.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.password_label.setObjectName("password_label")
        self.gridLayout.addWidget(self.password_label, 1, 0, 1, 1)
        self.remember_checkbox = QtWidgets.QCheckBox(parent=self.AccountFrame)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        self.remember_checkbox.setFont(font)
        self.remember_checkbox.setObjectName("remember_checkbox")
        self.gridLayout.addWidget(self.remember_checkbox, 2, 1, 1, 1)
        self.logout_account_btn = QtWidgets.QPushButton(parent=self.AccountFrame)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        self.logout_account_btn.setFont(font)
        self.logout_account_btn.setStyleSheet("color: rgb(255, 255, 0);")
        self.logout_account_btn.setObjectName("logout_account_btn")
        self.gridLayout.addWidget(self.logout_account_btn, 2, 4, 1, 1)
        self.login_btn = QtWidgets.QPushButton(parent=self.AccountFrame)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        self.login_btn.setFont(font)
        self.login_btn.setDefault(True)
        self.login_btn.setObjectName("login_btn")
        self.gridLayout.addWidget(self.login_btn, 2, 5, 1, 1)
        self.forget_account_btn = QtWidgets.QPushButton(parent=self.AccountFrame)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        self.forget_account_btn.setFont(font)
        self.forget_account_btn.setStyleSheet("color: rgb(255, 0, 0);")
        self.forget_account_btn.setDefault(True)
        self.forget_account_btn.setObjectName("forget_account_btn")
        self.gridLayout.addWidget(self.forget_account_btn, 2, 3, 1, 1)
        self.auto_login_checkbox = QtWidgets.QCheckBox(parent=self.AccountFrame)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        self.auto_login_checkbox.setFont(font)
        self.auto_login_checkbox.setObjectName("auto_login_checkbox")
        self.gridLayout.addWidget(self.auto_login_checkbox, 2, 2, 1, 1)
        self.gridLayout.setColumnStretch(0, 1)
        self.gridLayout.setColumnStretch(1, 2)
        self.gridLayout.setColumnStretch(2, 2)
        self.gridLayout.setColumnStretch(3, 2)
        self.gridLayout.setColumnStretch(4, 2)
        self.gridLayout.setColumnStretch(5, 2)
        self.problem_mode_table = QtWidgets.QTabWidget(parent=self.centralwidget)
        self.problem_mode_table.setGeometry(QtCore.QRect(560, 20, 891, 751))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.problem_mode_table.setFont(font)
        self.problem_mode_table.setTabShape(QtWidgets.QTabWidget.TabShape.Rounded)
        self.problem_mode_table.setObjectName("problem_mode_table")
        self.level_mode_page = QtWidgets.QWidget()
        self.level_mode_page.setObjectName("level_mode_page")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.level_mode_page)
        self.gridLayout_2.setSizeConstraint(
            QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint
        )
        self.gridLayout_2.setVerticalSpacing(20)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.problem_table = QtWidgets.QTableWidget(parent=self.level_mode_page)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.problem_table.setFont(font)
        self.problem_table.setAutoFillBackground(False)
        self.problem_table.setStyleSheet("")
        self.problem_table.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.problem_table.setHorizontalScrollBarPolicy(
            QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff
        )
        self.problem_table.setSizeAdjustPolicy(
            QtWidgets.QAbstractScrollArea.SizeAdjustPolicy.AdjustToContents
        )
        self.problem_table.setObjectName("problem_table")
        self.problem_table.setColumnCount(4)
        self.problem_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.problem_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.problem_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.problem_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.problem_table.setHorizontalHeaderItem(3, item)
        self.problem_table.horizontalHeader().setStretchLastSection(True)
        self.problem_table.verticalHeader().setVisible(False)
        self.gridLayout_2.addWidget(self.problem_table, 3, 0, 1, 9)
        self.submit_interval_spin = QtWidgets.QSpinBox(parent=self.level_mode_page)
        self.submit_interval_spin.setMinimum(10)
        self.submit_interval_spin.setMaximum(114514)
        self.submit_interval_spin.setProperty("value", 10)
        self.submit_interval_spin.setObjectName("submit_interval_spin")
        self.gridLayout_2.addWidget(self.submit_interval_spin, 4, 1, 1, 1)
        self.reverse_btn = QtWidgets.QPushButton(parent=self.level_mode_page)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        self.reverse_btn.setFont(font)
        self.reverse_btn.setObjectName("reverse_btn")
        self.gridLayout_2.addWidget(self.reverse_btn, 1, 6, 1, 1)
        self.cancel_submit_btn = QtWidgets.QPushButton(parent=self.level_mode_page)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cancel_submit_btn.setFont(font)
        self.cancel_submit_btn.setObjectName("cancel_submit_btn")
        self.gridLayout_2.addWidget(self.cancel_submit_btn, 4, 7, 1, 1)
        self.label_3 = QtWidgets.QLabel(parent=self.level_mode_page)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 4, 1, 1)
        self.choose_all_btn = QtWidgets.QPushButton(parent=self.level_mode_page)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        self.choose_all_btn.setFont(font)
        self.choose_all_btn.setObjectName("choose_all_btn")
        self.gridLayout_2.addWidget(self.choose_all_btn, 1, 5, 1, 1)
        self.auto_wait_submit_btn = QtWidgets.QPushButton(parent=self.level_mode_page)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.auto_wait_submit_btn.setFont(font)
        self.auto_wait_submit_btn.setObjectName("auto_wait_submit_btn")
        self.gridLayout_2.addWidget(self.auto_wait_submit_btn, 4, 6, 1, 1)
        self.label = QtWidgets.QLabel(parent=self.level_mode_page)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 6, 1, 1)
        self.auto_choose_btn = QtWidgets.QPushButton(parent=self.level_mode_page)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        self.auto_choose_btn.setFont(font)
        self.auto_choose_btn.setObjectName("auto_choose_btn")
        self.gridLayout_2.addWidget(self.auto_choose_btn, 1, 7, 1, 1)
        self.submit_btn = QtWidgets.QPushButton(parent=self.level_mode_page)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.submit_btn.setFont(font)
        self.submit_btn.setObjectName("submit_btn")
        self.gridLayout_2.addWidget(self.submit_btn, 4, 5, 1, 1)
        self.accounts_to_submit_box = QtWidgets.QComboBox(parent=self.level_mode_page)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.accounts_to_submit_box.setFont(font)
        self.accounts_to_submit_box.setEditable(False)
        self.accounts_to_submit_box.setInsertPolicy(
            QtWidgets.QComboBox.InsertPolicy.NoInsert
        )
        self.accounts_to_submit_box.setDuplicatesEnabled(False)
        self.accounts_to_submit_box.setObjectName("accounts_to_submit_box")
        self.gridLayout_2.addWidget(self.accounts_to_submit_box, 0, 7, 1, 1)
        self.label_2 = QtWidgets.QLabel(parent=self.level_mode_page)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 4, 0, 1, 1)
        self.language_combox = QtWidgets.QComboBox(parent=self.level_mode_page)
        self.language_combox.setObjectName("language_combox")
        self.language_combox.addItem("")
        self.language_combox.addItem("")
        self.language_combox.addItem("")
        self.language_combox.addItem("")
        self.language_combox.addItem("")
        self.language_combox.addItem("")
        self.language_combox.addItem("")
        self.language_combox.addItem("")
        self.language_combox.addItem("")
        self.language_combox.addItem("")
        self.gridLayout_2.addWidget(self.language_combox, 0, 5, 1, 1)
        self.cid_text = QtWidgets.QLineEdit(parent=self.level_mode_page)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cid_text.setFont(font)
        self.cid_text.setText("")
        self.cid_text.setMaxLength(10)
        self.cid_text.setClearButtonEnabled(True)
        self.cid_text.setObjectName("cid_text")
        self.gridLayout_2.addWidget(self.cid_text, 0, 0, 1, 1)
        self.detect_problem_btn = QtWidgets.QPushButton(parent=self.level_mode_page)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        self.detect_problem_btn.setFont(font)
        self.detect_problem_btn.setObjectName("detect_problem_btn")
        self.gridLayout_2.addWidget(self.detect_problem_btn, 0, 1, 1, 1)
        self.auto_detect_checkbox = QtWidgets.QCheckBox(parent=self.level_mode_page)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.auto_detect_checkbox.setFont(font)
        self.auto_detect_checkbox.setObjectName("auto_detect_checkbox")
        self.gridLayout_2.addWidget(self.auto_detect_checkbox, 0, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(parent=self.level_mode_page)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 1, 0, 1, 1)
        self.problem_status_label = QtWidgets.QLabel(parent=self.level_mode_page)
        self.problem_status_label.setStyleSheet(
            "text-decoration: underline;\n" 'font: 12pt "Microsoft YaHei UI";'
        )
        self.problem_status_label.setObjectName("problem_status_label")
        self.gridLayout_2.addWidget(self.problem_status_label, 1, 1, 1, 1)
        self.force_submit_checkbox = QtWidgets.QCheckBox(parent=self.level_mode_page)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.force_submit_checkbox.setFont(font)
        self.force_submit_checkbox.setObjectName("force_submit_checkbox")
        self.gridLayout_2.addWidget(self.force_submit_checkbox, 4, 2, 1, 1)
        self.gridLayout_2.setColumnStretch(0, 1)
        self.gridLayout_2.setColumnStretch(1, 1)
        self.gridLayout_2.setColumnStretch(2, 1)
        self.gridLayout_2.setColumnStretch(4, 1)
        self.gridLayout_2.setColumnStretch(5, 1)
        self.gridLayout_2.setColumnStretch(6, 1)
        self.gridLayout_2.setColumnStretch(7, 1)
        self.problem_mode_table.addTab(self.level_mode_page, "")
        self.bank_mode_page = QtWidgets.QWidget()
        self.bank_mode_page.setObjectName("bank_mode_page")
        self.textBrowser = QtWidgets.QTextBrowser(parent=self.bank_mode_page)
        self.textBrowser.setGeometry(QtCore.QRect(160, 230, 551, 141))
        self.textBrowser.setObjectName("textBrowser")
        self.problem_mode_table.addTab(self.bank_mode_page, "")
        self.log_browser = QtWidgets.QTextBrowser(parent=self.centralwidget)
        self.log_browser.setGeometry(QtCore.QRect(20, 230, 521, 391))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        self.log_browser.setFont(font)
        self.log_browser.setStyleSheet(
            "background-color: rgb(59, 59, 59);\n"
            'font: 700 12pt "Microsoft YaHei UI";'
        )
        self.log_browser.setObjectName("log_browser")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(20, 640, 521, 131))
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.gridLayoutWidget = QtWidgets.QWidget(parent=self.frame)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 521, 131))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_4.setContentsMargins(12, 6, 12, 6)
        self.gridLayout_4.setHorizontalSpacing(18)
        self.gridLayout_4.setVerticalSpacing(12)
        self.gridLayout_4.setObjectName("gridLayout_4")
        spacerItem = QtWidgets.QSpacerItem(
            20,
            40,
            QtWidgets.QSizePolicy.Policy.Minimum,
            QtWidgets.QSizePolicy.Policy.Expanding,
        )
        self.gridLayout_4.addItem(spacerItem, 1, 1, 1, 1)
        self.about_btn = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.about_btn.setFont(font)
        self.about_btn.setObjectName("about_btn")
        self.gridLayout_4.addWidget(self.about_btn, 2, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(
            40,
            20,
            QtWidgets.QSizePolicy.Policy.Expanding,
            QtWidgets.QSizePolicy.Policy.Minimum,
        )
        self.gridLayout_4.addItem(spacerItem1, 2, 1, 1, 1)
        self.reset_all_btn = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.reset_all_btn.setFont(font)
        self.reset_all_btn.setObjectName("reset_all_btn")
        self.gridLayout_4.addWidget(self.reset_all_btn, 0, 0, 1, 1)
        self.gridLayout_4.setColumnStretch(0, 1)
        self.gridLayout_4.setColumnStretch(1, 3)
        self.gridLayout_4.setColumnStretch(2, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.problem_mode_table.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "OJSubmitter"))
        self.account_label.setText(
            _translate(
                "MainWindow",
                '<html><head/><body><p align="center">账号</p></body></html>',
            )
        )
        self.password_label.setText(
            _translate(
                "MainWindow",
                '<html><head/><body><p align="center">密码</p></body></html>',
            )
        )
        self.remember_checkbox.setText(_translate("MainWindow", "记住该账号"))
        self.logout_account_btn.setText(_translate("MainWindow", "登出"))
        self.login_btn.setText(_translate("MainWindow", "登入"))
        self.forget_account_btn.setText(_translate("MainWindow", "删除"))
        self.auto_login_checkbox.setText(_translate("MainWindow", "自动登入"))
        item = self.problem_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "答题"))
        item = self.problem_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "状态"))
        item = self.problem_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "题目ID"))
        item = self.problem_table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "题目标题"))
        self.reverse_btn.setText(_translate("MainWindow", "反选"))
        self.cancel_submit_btn.setText(_translate("MainWindow", "取消提交"))
        self.label_3.setText(
            _translate(
                "MainWindow",
                '<html><head/><body><p align="right">语言</p></body></html>',
            )
        )
        self.choose_all_btn.setText(_translate("MainWindow", "全选/全不选"))
        self.auto_wait_submit_btn.setToolTip(
            _translate(
                "MainWindow",
                "题目还未开启时，此按钮可以等待指定课程号的开启并自动开始提交未完成的题目",
            )
        )
        self.auto_wait_submit_btn.setText(_translate("MainWindow", "自动等待并提交"))
        self.label.setText(
            _translate(
                "MainWindow",
                '<html><head/><body><p align="right">当前账号: </p></body></html>',
            )
        )
        self.auto_choose_btn.setText(_translate("MainWindow", "仅选未完成"))
        self.submit_btn.setText(_translate("MainWindow", "开始提交"))
        self.label_2.setText(
            _translate(
                "MainWindow",
                '<html><head/><body><p align="right">提交间隔(s)</p></body></html>',
            )
        )
        self.language_combox.setItemText(0, _translate("MainWindow", "c"))
        self.language_combox.setItemText(1, _translate("MainWindow", "cpp"))
        self.language_combox.setItemText(2, _translate("MainWindow", "pas"))
        self.language_combox.setItemText(3, _translate("MainWindow", "java"))
        self.language_combox.setItemText(4, _translate("MainWindow", "ruby"))
        self.language_combox.setItemText(5, _translate("MainWindow", "bash"))
        self.language_combox.setItemText(6, _translate("MainWindow", "py"))
        self.language_combox.setItemText(7, _translate("MainWindow", "php"))
        self.language_combox.setItemText(8, _translate("MainWindow", "perl"))
        self.language_combox.setItemText(9, _translate("MainWindow", "csharp"))
        self.cid_text.setPlaceholderText(_translate("MainWindow", "课程号"))
        self.detect_problem_btn.setText(_translate("MainWindow", "检测"))
        self.auto_detect_checkbox.setToolTip(
            _translate("MainWindow", "勾选后 当课程号更新自动进行检测")
        )
        self.auto_detect_checkbox.setText(_translate("MainWindow", "自动检测"))
        self.label_4.setText(
            _translate(
                "MainWindow",
                '<html><head/><body><p align="right">关卡状态:</p></body></html>',
            )
        )
        self.problem_status_label.setText(
            _translate(
                "MainWindow",
                '<html><head/><body><p align="center">未知</p></body></html>',
            )
        )
        self.force_submit_checkbox.setToolTip(
            _translate("MainWindow", "无论是否可提交，仍然尝试发送请求")
        )
        self.force_submit_checkbox.setText(_translate("MainWindow", "强制提交"))
        self.problem_mode_table.setTabText(
            self.problem_mode_table.indexOf(self.level_mode_page),
            _translate("MainWindow", "🕙关卡模式🕙"),
        )
        self.textBrowser.setHtml(
            _translate(
                "MainWindow",
                '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">\n'
                '<html><head><meta name="qrichtext" content="1" /><meta charset="utf-8" /><style type="text/css">\n'
                "p, li { white-space: pre-wrap; }\n"
                "hr { height: 1px; border-width: 0; }\n"
                'li.unchecked::marker { content: "\\2610"; }\n'
                'li.checked::marker { content: "\\2612"; }\n'
                "</style></head><body style=\" font-family:'Microsoft YaHei UI'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
                '<p align="center" style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-size:36pt;">题库模式未实现</span></p>\n'
                '<p align="center" style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-size:36pt;">敬请期待</span></p></body></html>',
            )
        )
        self.problem_mode_table.setTabText(
            self.problem_mode_table.indexOf(self.bank_mode_page),
            _translate("MainWindow", "📖题库模式📖"),
        )
        self.log_browser.setHtml(
            _translate(
                "MainWindow",
                '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">\n'
                '<html><head><meta name="qrichtext" content="1" /><meta charset="utf-8" /><style type="text/css">\n'
                "p, li { white-space: pre-wrap; }\n"
                "hr { height: 1px; border-width: 0; }\n"
                'li.unchecked::marker { content: "\\2610"; }\n'
                'li.checked::marker { content: "\\2612"; }\n'
                "</style></head><body style=\" font-family:'Microsoft YaHei UI'; font-size:12pt; font-weight:700; font-style:normal;\">\n"
                '<p style="-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:9pt; font-weight:400;"><br /></p></body></html>',
            )
        )
        self.about_btn.setText(_translate("MainWindow", "关于"))
        self.reset_all_btn.setText(_translate("MainWindow", "重置所有"))
