from enum import StrEnum


class LogSourceEnum(StrEnum):
    ACCOUNT_AUTH_SYSTEM = "A-A-SYS"
    ACCOUNT_COOKIE_SYSTEM = "A-C-SYS"

    PROBLEM_SELECTION_SYSTEM = "P-SL-SYS"
    PROBLEM_DETECT_SYSTEM = "P-D-SYS"
    PROBLEM_SUBMIT_SYSTEM = "P-S-SYS"

    SETTING_OPERATION_SYSTEM = "S-O-SYS"
    SETTING_INFORMATION_SYSTEM = "S-I-SYS"
